### ISSUE TITLE
CMake on Mac OS X

### ISSUE THREAD

**Issue by abhishekdewan101** [Norman0406/OpenSkeletonFitting#1]
When you try building the files using the CMakeLists.txt file in the root folder its spits out the following error

DISSECT_VERSION()
GET_OS_INFO() not defined. 

is there something that I am doing wrong ?

**Comment by Norman0406** [comment]
This is related to the CMinPack dependency. I don't have access to a Mac anymore, you could try to build CMinPack separately first and see what's stopping it from building.
You can also try to remove CMinPack from the project, since it is not strictly necessary, and comment out the code that depends on it.

**Comment by Norman0406** [comment]
Closing this issue.
